name: "GitHub Pages"

on:
  workflow_dispatch:
  push:

concurrency:
  group: "doc"
  cancel-in-progress: true

jobs:
  doc:
    name: "Deploy pages"

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Disable initramfs update
      run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
    - name: Disable man-db update
      run: sudo rm -f /var/lib/man-db/auto-update
    - name: Setup Taiga
      run: cd www && wget https://j.nishi.boats/job/pyrite-dev/job/taiga/job/master/lastSuccessfulBuild/artifact/taiga-linux64 -O taiga && chmod +x taiga
    - name: Build site
      run: cd www && ./taiga
    - name: Setup pages
      uses: actions/configure-pages@v4
    - name: Upload pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: "www/build"
    - name: Deploy pages
      uses: actions/deploy-pages@v4
